#!/bin/sh

DAEMON=/usr/bin/aesdsocket
DAEMON_NAME=aesdsocket
PIDFILE=/var/run/$DAEMON_NAME.pid
DAEMON_OPTS="-d"

case "$1" in
  start)
    echo "Starting $DAEMON_NAME..."
    start-stop-daemon -S -n $DAEMON_NAME -a $DAEMON -- $DAEMON_OPTS
    ;;
  stop)
    echo "Stopping $DAEMON_NAME..."
    start-stop-daemon -K -n $DAEMON_NAME
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0

